# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    # Step 1: Create a VM to test your code on
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 2: Obtain the repo from GitHub
      - checkout
      # Step 3: Create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator